### ISSUE TITLE
Custom SQL selectors and referenceFormulation

### ISSUE THREAD

**Issue by cordawyn** [RMLio/rmlmapper-java#12]
It all started with me trying to use a custom SQL query in `rml:logicalSource`:

```
<#PersonTriples> a rr:TriplesMap ;
  rml:logicalSource [
    rml:source <#testDB> ;
    rr:sqlVersion rr:SQL2008 ;
    rml:referenceFormulation rr:SQL2008 ;
    rr:sqlQuery "SELECT name, email, product FROM surveys" ] ;
...
```

First, it could not find my query:

```
Exception in thread "main" java.lang.Error: The Logical Source of <http://example.com/base/#PersonTriples> does not include a SQL query nor a target table.
        at be.ugent.rml.records.RecordsFactory.getRDBsRecords(RecordsFactory.java:201)
        at be.ugent.rml.records.RecordsFactory.createRecords(RecordsFactory.java:87)
        at be.ugent.rml.Executor.getRecords(Executor.java:252)
        at be.ugent.rml.Executor.execute(Executor.java:58)
        at be.ugent.rml.cli.Main.main(Main.java:130)
```

A brief look-up in the sources revealed that `rmlmapper` actually expects `rr:query` instead of `rr:sqlQuery`. Moreover, the comparison table at http://rml.io/RML_R2RML.html mentions "rr:SQLQuery" which makes it even more confusing – "sql" should be in lower case there.

I think it still should be "rr:sqlQuery" as per R2RML specs.

Anyway, I replaced "rr:sqlQuery" with "rr:query", but then another error popped up:

```
Exception in thread "main" java.lang.Error: Unsupported rml:referenceFormulation for RDB source: http://www.w3.org/ns/r2rml#SQL2008
        at be.ugent.rml.records.RDBs.get(RDBs.java:60)
        at be.ugent.rml.records.RecordsFactory.getRDBsRecords(RecordsFactory.java:235)
        at be.ugent.rml.records.RecordsFactory.createRecords(RecordsFactory.java:87)
        at be.ugent.rml.Executor.getRecords(Executor.java:252)
        at be.ugent.rml.Executor.execute(Executor.java:58)
        at be.ugent.rml.cli.Main.main(Main.java:130)
```
It looks like it's indeed unsupported in `rmlmapper` judging by the source code, but it seems to be a valid RDB source and there's plenty examples with it throughout the RML specs (http://rml.io/spec.html).

Is it indeed all broken/unsupported or am I missing something?

Thank you!

**Comment by pheyvaer** [comment]
> It all started with me trying to use a custom SQL query in `rml:logicalSource`:
> 
> ```
> <#PersonTriples> a rr:TriplesMap ;
>   rml:logicalSource [
>     rml:source <#testDB> ;
>     rr:sqlVersion rr:SQL2008 ;
>     rml:referenceFormulation rr:SQL2008 ;
>     rr:sqlQuery "SELECT name, email, product FROM surveys" ] ;
> ...
> ```
> 
> First, it could not find my query:
> 
> ```
> Exception in thread "main" java.lang.Error: The Logical Source of <http://example.com/base/#PersonTriples> does not include a SQL query nor a target table.
>         at be.ugent.rml.records.RecordsFactory.getRDBsRecords(RecordsFactory.java:201)
>         at be.ugent.rml.records.RecordsFactory.createRecords(RecordsFactory.java:87)
>         at be.ugent.rml.Executor.getRecords(Executor.java:252)
>         at be.ugent.rml.Executor.execute(Executor.java:58)
>         at be.ugent.rml.cli.Main.main(Main.java:130)
> ```
> 
> A brief look-up in the sources revealed that `rmlmapper` actually expects `rr:query` instead of `rr:sqlQuery`. Moreover, the comparison table at http://rml.io/RML_R2RML.html mentions "rr:SQLQuery" which makes it even more confusing – "sql" should be in lower case there.
> 
> I think it still should be "rr:sqlQuery" as per R2RML specs.
> 
> Anyway, I replaced "rr:sqlQuery" with "rr:query", but then another error popped up:
> 
> ```
> Exception in thread "main" java.lang.Error: Unsupported rml:referenceFormulation for RDB source: http://www.w3.org/ns/r2rml#SQL2008
>         at be.ugent.rml.records.RDBs.get(RDBs.java:60)
>         at be.ugent.rml.records.RecordsFactory.getRDBsRecords(RecordsFactory.java:235)
>         at be.ugent.rml.records.RecordsFactory.createRecords(RecordsFactory.java:87)
>         at be.ugent.rml.Executor.getRecords(Executor.java:252)
>         at be.ugent.rml.Executor.execute(Executor.java:58)
>         at be.ugent.rml.cli.Main.main(Main.java:130)
> ```
> 
> It looks like it's indeed unsupported in `rmlmapper` judging by the source code, but it seems to be a valid RDB source and there's plenty examples with it throughout the RML specs (http://rml.io/spec.html).
> 
> Is it indeed all broken/unsupported or am I missing something?
> 
> Thank you!

**Comment by bjdmeest** [comment]
@cordawyn this should now work in our latest release (https://github.com/RMLio/rmlmapper-java/releases/tag/v4.3.2), using `rml:query`, could you verify?

**Comment by cordawyn** [comment]
Sure, I'll give it a try!

**Comment by cordawyn** [comment]
@bjdmeest Even though "rml:query" seems to work, `rr:SQL2008` is still not supported as a `rml:referenceFormulation`:
https://github.com/RMLio/rmlmapper-java/blob/5480a36a69659f793225877c9ea1558151e52d0a/src/main/java/be/ugent/rml/records/RDBs.java#L53

... so my example still doesn't work 😄

**Comment by pheyvaer** [comment]
Hi @cordawyn,

The reference formulation should not be `rr:SQL2008`, because the results returned by an SQL query are a table and not another SQL database on which you can do another query. In our case we consider this table to be the same as CSV. So removing `rml:referenceFormulation rr:SQL2008 ` should work. You can find a working example [here](https://github.com/RMLio/rml-test-cases/blob/master/test-cases/RMLTC0011a-MySQL/mapping.ttl).

**Comment by cordawyn** [comment]
I see. I tried it with CSV, and it worked. Thank you!
(Although "CSV" is really misleading name in this case, IMHO).

Anyway, we can close this issue, I believe.
