### ISSUE TITLE
question regarding functions: transform strings for IRI creation

### ISSUE THREAD

**Issue by mathib** [RMLio/rmlmapper-java#44]
Hi! I would like to transform all string values of a TSV column into an IRI. The problem is the string values contain several not allowed characters such as spaces, commas, (round) brackets, etc. I would like to transform them as follows:
* remove all commas
* replace "(" by "-"
* remove all ")"
* use PascalCase (or camelCase) over string

example string input: "an example, string (remark)"
output IRI: `<http://mydomain.org/data#AnExampleString-remark>`

I experimented a little bit with a single function as described in the [FNO spec](https://fno.io/rml/). I copied the [functions.ttl](https://github.com/RMLio/rmlmapper-java/blob/master/src/main/resources/functions.ttl) and [GrelFunctions.jar](https://github.com/RMLio/rmlmapper-java/blob/master/src/main/resources/GrelFunctions.jar) from this repo into the repo where the RML-mapper jar is (dynamic loading). On execution, the RML-mapper returns an error:
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at be.ugent.rml.functions.DynamicMultipleRecordsFunctionExecutor.execute(DynamicMultipleRecordsFunctionExecutor.java:66)
        at be.ugent.rml.functions.AbstractSingleRecordFunctionExecutor.execute(AbstractSingleRecordFunctionExecutor.java:16)
        at be.ugent.rml.termgenerator.LiteralGenerator.generate(LiteralGenerator.java:54)
        at be.ugent.rml.Executor.generatePredicateObjectGraphs(Executor.java:192)
        at be.ugent.rml.Executor.executeWithFunction(Executor.java:150)
        at be.ugent.rml.Executor.execute(Executor.java:77)
        at be.ugent.rml.cli.Main.main(Main.java:223)
        at be.ugent.rml.cli.Main.main(Main.java:30)
```

**Comment by mathib** [comment]
I noticed FNO changed from namespace, but I don't think it's related as the error remains the same:
old namespace: `@prefix fno: <http://semweb.datasciencelab.be/ns/function#> .`
new namespace: `@prefix fno: <https://w3id.org/function/ontology#> .`

**Comment by mathib** [comment]
This zip contains a TSV file and a mapping with two examples:

[minimalExample.zip](https://github.com/RMLio/rmlmapper-java/files/3772321/minimalExample.zip)

In the first example, a function is executed on the subjectmap (grel:UpperCaseURL), while in the second example a function is executed on the objectmap (grel:UpperCase)

From the moment this works, I need to find how to make nested functions, e.g. using a remove, replace and PascalCase/camelCase function. Pointers are welcome :)

**Comment by bjdmeest** [comment]
Great, we'll have a look! Meanwhile, you can check http://rml.io/yarrrml/spec/#functions for nested functions
(we've been developing [YARRRML](http://rml.io/yarrrml/) to more easily create RML rules, you can try it out [online](http://rml.io/yarrrml/matey/) if you want)

**Comment by pheyvaer** [comment]
@mathib 
> From the moment this works

Is the initial error of this issue still occurring then?

**Comment by mathib** [comment]
@pheyvaer : Yes, still having the same error wit plain RML (I'll try to stick with RML for the moment). From the link of @bjdmeest , I learned how to combine functions, but I cannot get an individual function working (e.g. I tried the `grel:toUpperCase` and `grel:toUpperCaseURL` functions but without success)

**Comment by pheyvaer** [comment]
Hi @mathib 

There was an issue with the namespace of FnO (http vs https). This should be fixed now in the RMLMapper with the [latest release](https://github.com/RMLio/rmlmapper-java/releases/tag/v4.6.0). Can you have a look and see if the functions now work on your side?

**Comment by mathib** [comment]
No sorry, it still doesn't work for me. Did it worked on your side on the small sample mapping and sample data? I receive the following list of exceptions:

```
java.lang.Exception: Mapping requires at least one TriplesMap
        at be.ugent.rml.conformer.MappingConformer.detect(MappingConformer.java:80)
        at be.ugent.rml.conformer.MappingConformer.conform(MappingConformer.java:55)
        at be.ugent.rml.cli.Main.main(Main.java:178)
        at be.ugent.rml.cli.Main.main(Main.java:35)
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at be.ugent.rml.functions.FunctionModel.execute(FunctionModel.java:39)
        at be.ugent.rml.functions.DynamicMultipleRecordsFunctionExecutor.execute(DynamicMultipleRecordsFunctionExecutor.java:74)
        at be.ugent.rml.functions.AbstractSingleRecordFunctionExecutor.execute(AbstractSingleRecordFunctionExecutor.java:16)
        at be.ugent.rml.termgenerator.NamedNodeGenerator.generate(NamedNodeGenerator.java:22)
        at be.ugent.rml.Executor.getSubject(Executor.java:298)
        at be.ugent.rml.Executor.executeWithFunction(Executor.java:94)
        at be.ugent.rml.Executor.execute(Executor.java:77)
        at be.ugent.rml.cli.Main.main(Main.java:274)
        at be.ugent.rml.cli.Main.main(Main.java:35)
Caused by: java.lang.NullPointerException
        at be.ugent.rml.functions.lib.GrelProcessor.toUpperCaseURL(GrelProcessor.java:32)
        ... 13 more
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at be.ugent.rml.functions.FunctionModel.execute(FunctionModel.java:39)
        at be.ugent.rml.functions.DynamicMultipleRecordsFunctionExecutor.execute(DynamicMultipleRecordsFunctionExecutor.java:74)
        at be.ugent.rml.functions.AbstractSingleRecordFunctionExecutor.execute(AbstractSingleRecordFunctionExecutor.java:16)
        at be.ugent.rml.termgenerator.NamedNodeGenerator.generate(NamedNodeGenerator.java:22)
        at be.ugent.rml.Executor.getSubject(Executor.java:298)
        at be.ugent.rml.Executor.executeWithFunction(Executor.java:94)
        at be.ugent.rml.Executor.execute(Executor.java:77)
        at be.ugent.rml.cli.Main.main(Main.java:274)
        at be.ugent.rml.cli.Main.main(Main.java:35)
Caused by: java.lang.NullPointerException
        at be.ugent.rml.functions.lib.GrelProcessor.toUpperCaseURL(GrelProcessor.java:32)
        ... 13 more
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at be.ugent.rml.functions.FunctionModel.execute(FunctionModel.java:39)
        at be.ugent.rml.functions.DynamicMultipleRecordsFunctionExecutor.execute(DynamicMultipleRecordsFunctionExecutor.java:74)
        at be.ugent.rml.functions.AbstractSingleRecordFunctionExecutor.execute(AbstractSingleRecordFunctionExecutor.java:16)
        at be.ugent.rml.termgenerator.LiteralGenerator.generate(LiteralGenerator.java:54)
        at be.ugent.rml.Executor.generatePredicateObjectGraphs(Executor.java:192)
        at be.ugent.rml.Executor.executeWithFunction(Executor.java:150)
        at be.ugent.rml.Executor.execute(Executor.java:77)
        at be.ugent.rml.cli.Main.main(Main.java:274)
        at be.ugent.rml.cli.Main.main(Main.java:35)
Caused by: java.lang.NullPointerException
        at be.ugent.rml.functions.lib.GrelProcessor.toUppercase(GrelProcessor.java:10)
        ... 13 more
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at be.ugent.rml.functions.FunctionModel.execute(FunctionModel.java:39)
        at be.ugent.rml.functions.DynamicMultipleRecordsFunctionExecutor.execute(DynamicMultipleRecordsFunctionExecutor.java:74)
        at be.ugent.rml.functions.AbstractSingleRecordFunctionExecutor.execute(AbstractSingleRecordFunctionExecutor.java:16)
        at be.ugent.rml.termgenerator.LiteralGenerator.generate(LiteralGenerator.java:54)
        at be.ugent.rml.Executor.generatePredicateObjectGraphs(Executor.java:192)
        at be.ugent.rml.Executor.executeWithFunction(Executor.java:150)
        at be.ugent.rml.Executor.execute(Executor.java:77)
        at be.ugent.rml.cli.Main.main(Main.java:274)
        at be.ugent.rml.cli.Main.main(Main.java:35)
Caused by: java.lang.NullPointerException
        at be.ugent.rml.functions.lib.GrelProcessor.toUppercase(GrelProcessor.java:10)
        ... 13 more
```
I'm using Java 8 and all files are in the same folder (`GrelFunctions.jar`, `functions.ttl`, `rmlmapper.jar`, my test data (`test_tab_file1.tsv`) and test RML mapping (`RML_withFunctions_example.ttl`))

What is now the correct namespace for FnO? I'm also unsure if I should use `grel:valueParam` or `grel:inputString`

**Comment by pheyvaer** [comment]
You can find a working RML doc below.
Two things were missing/wrong:
- There were no TriplesMaps in the RML file (which is also mentioned in the error). I've added `a rr:TriplesMap` twice in the file.
- To point to the values to be used by the function you need to use `grel:valueParameter`. `grel:valueParam` _describes_ the parameter, but is not the predicate to be used to connect the parameter with the function during execution.

The correct namespace for FnO is `https://w3id.org/function/ontology#`.

```
@base <http://example.org/data> .
@prefix rr: <http://www.w3.org/ns/r2rml#> .
@prefix rml: <http://semweb.mmlab.be/ns/rml#> .
@prefix ql: <http://semweb.mmlab.be/ns/ql#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix csvw: <http://www.w3.org/ns/csvw#> .
@prefix fnml: <http://semweb.mmlab.be/ns/fnml#> .
#@prefix fno: <http://semweb.datasciencelab.be/ns/function#> .	# old namespace
@prefix fno: <https://w3id.org/function/ontology#> .			# new namespace
@prefix grel: <http://users.ugent.be/~bjdmeest/function/grel.ttl#> .

## function map 1
<#functionMap-toUpperCase>
	fnml:functionValue [
        rml:logicalSource <#CSVW_source1> ;
		#rr:subjectMap [] ;
        rr:predicateObjectMap [
            rr:predicate fno:executes ;
			rr:objectMap [ rr:constant grel:toUpperCase ]		# used for second example
        ] ;
        rr:predicateObjectMap [
            rr:predicate grel:valueParameter ; 						# does not work
			#rr:predicate grel:inputString ; 					# does not work either (based on example in https://fno.io/rml/)
            rr:objectMap [
				rml:reference "D1"								# does not work
			]
        ]
    ] .

## function map 2
<#functionMap-toUpperCaseURL>
	fnml:functionValue [
        rml:logicalSource <#CSVW_source1> ;
		#rr:subjectMap [] ;
        rr:predicateObjectMap [
            rr:predicate fno:executes ;
            rr:objectMap [ rr:constant grel:toUpperCaseURL ] 	# used for first example
        ] ;
        rr:predicateObjectMap [
            rr:predicate grel:valueParameter ; 						# does not work
			#rr:predicate grel:inputString ; 					# does not work either (based on example in https://fno.io/rml/)
            rr:objectMap [
				rr:template "https://mydomain.org/data#{D1}"	# does not work
			]
        ]
    ] .

## working with TSV files
<#CSVW_source1> a csvw:Table ; # must be full IRI (not <#CSVW_source> as in example)
   csvw:url "test_tab_file1.tsv" ;
   csvw:dialect [
		a csvw:Dialect ;
		csvw:delimiter "\t"
   ] .

### first example: function over input of subject map
<#mapping-D1-functionOnSubject> a rr:TriplesMap;
	rml:logicalSource [
		rml:source <#CSVW_source1> ;
		rml:referenceFormulation ql:CSV
	] ;
	rr:subjectMap <#functionMap-toUpperCaseURL> ; 					# functionsmap on subject fails
	rr:predicateObjectMap [
		rr:predicate rdfs:label ;
		rr:objectMap
		[
			rml:reference "D1" ;
		]
	] .

### second example: function over input of object map
<#mapping-D1-functionOnObject> a rr:TriplesMap;
	rml:logicalSource [
		rml:source <#CSVW_source1> ;
		rml:referenceFormulation ql:CSV
	] ;
	rr:subjectMap
	[
		rr:template "https://mydomain.org/data#{D1}" ; 			# result is D1 urlencoded
		rr:class owl:Class
	] ;
	rr:predicateObjectMap [
		rr:predicate rdfs:label ;
		rr:objectMap <#functionMap-toUpperCase>
	] .
```

Hope this helps :smiley:

**Comment by mathib** [comment]
thanks that works! In the previous version, it wasn't mandatory to classify a node explicitly as a `rr:TriplesMap`. This example might save others some headaches 😄

**Comment by mathib** [comment]
are there actually any public functions available to **replace** parts of a string, during the processing with the RML mapper app? I found this overview on your [website](https://fno.io/hub/functionInfo/https%253A%252F%252Ffno.io%252Fhub%252Fdata%252Fresource%252FFunction%252Freplace) but none of those functions are in functions.ttl. What would also be handy is a function to generate PascalCase/camelCase from an input string

**Comment by pheyvaer** [comment]
At the moment not. We are working on adding more common-used functions, including a replace function. You can always add functions yourself if needed immediately though. This is explained [here](https://github.com/RMLio/rmlmapper-java#including-functions).
